sudo: true
language: node_js
node_js:
- stable
git:
  quiet: true
cache: npm
before_install:
- openssl aes-256-cbc -K $encrypted_4752afa95b8a_key -iv $encrypted_4752afa95b8a_iv
  -in ./deploy/travis_rsa.enc -out ./deploy/travis_rsa -d
- chmod 600 ./deploy/travis_rsa
- mv ./deploy/travis_rsa ~/.ssh/id_rsa
- cat ./deploy/server.pub >> $HOME/.ssh/known_hosts
after_success:
- bash ./deploy/deploy.sh
